package lrcbuilder;

import javax.swing.JOptionPane;
import javax.swing.text.DefaultCaret;

/**
 * Settings editor.
 *
 * @author Aldo Kalid Hernández Camarena.
 */
public class SettingsEditor extends javax.swing.JDialog {

    public static final String PREV_1 = """
                                        [tl:Requiem For My Harlequin]
                                        [ar:Poets of the fall]
                                        [al:Ghostlight]
                                        """;
    public static final String PREV_2 = """
                                        [00:30.00]This is the requiem for the harlequin
                                        [00:35.01]The great pretender crashing down with style.
                                        [00:41.10]Here's to the fall of man
                                        [00:46.35]fame to dust, fortune to sand
                                        [00:50.10]The great surrender finally arrived
                                        ...""";
    public static final String PREV_3 = """
                                        [00:30.00]This is the requiem for the harlequin
                                        [00:35.01]The great pretender crashing down with style.
                                        [00:39.47]
                                        [00:41.10]Here's to the fall of man
                                        [00:46.35]Fame to dust, fortune to sand
                                        [00:50.10]The great surrender finally arrived
                                        [00:53.98]
                                        ...""";
    private Setting s;

    public SettingsEditor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        s = new DAOIO<Setting>(new Global().getFilePath(Global.SETTING_FILE)).read();
        if (s == null) {
            s = new Setting();
        }

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        delayTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        empLinChBx = new javax.swing.JCheckBox();
        tagChBx = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lyricTxt = new javax.swing.JTextArea();
        DefaultCaret caret = (DefaultCaret) lyricTxt.getCaret();
        caret.setUpdatePolicy(DefaultCaret.NEVER_UPDATE);
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("LRC Builder preferences");

        jLabel2.setText("Theme");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Light", "Dark" }));
        jComboBox1.setSelectedIndex(s.getTheme());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/quest.png"))); // NOI18N
        jLabel3.setText("Time delay");
        jLabel3.setToolTipText("After clicking build button, lyrics will be saved\nwith the specified time delay (ex. if delay is set\nat '00:01.00' and lyirc was captured at '01:01.00',\nthen lyric timer will be saved at '01:00.00').");

        delayTxt.setEditable(false);
        delayTxt.setText(s.getDelay().toString());
        delayTxt.setToolTipText("Not supported yet.");
        delayTxt.setEnabled(false);

        jButton1.setText("Edit");
        jButton1.setToolTipText("Not supported yet.");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("UI");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Lyric edit and export");

        empLinChBx.setSelected(s.getAddEmptyLines());
        empLinChBx.setText("Always add empty or blank lines.");
        empLinChBx.setToolTipText("Lines with no letters or only with spaces will be skyped");
        empLinChBx.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ChBxItemStateChanged(evt);
            }
        });

        tagChBx.setSelected(s.getSaveTags());
        tagChBx.setText("Save song tags");
        tagChBx.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ChBxItemStateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Export preview");

        lyricTxt.setEditable(false);
        lyricTxt.setColumns(20);
        lyricTxt.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        lyricTxt.setRows(5);
        lyricTxt.setText(s.getSaveTags() ? (PREV_1.concat(s.getAddEmptyLines() ? PREV_3 : PREV_2)) : (s.getAddEmptyLines() ? PREV_3 : PREV_2));
        lyricTxt.setAutoscrolls(false);
        jScrollPane1.setViewportView(lyricTxt);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Player builder");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tagChBx)
                                    .addComponent(empLinChBx)
                                    .addComponent(jLabel6)))
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(delayTxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empLinChBx)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tagChBx)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(delayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ChBxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ChBxItemStateChanged
        lyricTxt.setText(tagChBx.isSelected() ? PREV_1.concat(empLinChBx.isSelected()
                ? PREV_3 : PREV_2) : (empLinChBx.isSelected() ? PREV_3 : PREV_2));
    }//GEN-LAST:event_ChBxItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new TimeEditor((java.awt.Frame) this.getParent(), true, s.getDelay()).setVisible(true);
        delayTxt.setText(s.getDelay().toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (s != null) {
            if (s.getTheme() != jComboBox1.getSelectedIndex()) {
                JOptionPane.showMessageDialog(this, "Restart the program to apply theme.",
                        "Theme changed.", JOptionPane.INFORMATION_MESSAGE);
            }

            s.setTheme(jComboBox1.getSelectedIndex());
            s.setDelay(Time.splitTime(delayTxt.getText()));
            s.setAddEmptyLines(empLinChBx.isSelected());
            s.setSaveTags(tagChBx.isSelected());

            new DAOIO<Setting>(new Global().getFilePath(Global.SETTING_FILE)).write(s);
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField delayTxt;
    private javax.swing.JCheckBox empLinChBx;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea lyricTxt;
    private javax.swing.JCheckBox tagChBx;
    // End of variables declaration//GEN-END:variables
}
