package lrcbuilder;

import javax.swing.JTextField;

/**
 * Time editor.
 *
 * @author Aldo Kalid Hernández Camarena
 */
public class TimeEditor extends javax.swing.JDialog {

    private final Time time;

    public TimeEditor(java.awt.Frame parent, boolean modal, Time time) {
        super(parent, modal);

        this.time = time == null ? new Time() : time;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        secTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        milTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        okBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Time editor");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        minTxt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        minTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        minTxt.setText(time.getMinutes());
        minTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtFocusLost(evt);
            }
        });
        minTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                minTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(":");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        secTxt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        secTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        secTxt.setText(time.getSeconds());
        secTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtFocusLost(evt);
                jTxtFocusLostNormalize(evt);
            }
        });
        secTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                secTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(".");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        milTxt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        milTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        milTxt.setText(time.getMiliseconds());
        milTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtFocusLost(evt);
            }
        });
        milTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                milTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtKeyTyped(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Change the time as wished.");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Minutes");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Seconds");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Miliseconds");

        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(minTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(secTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(milTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(secTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(milTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtKeyTyped
        JTextField jTxt = (JTextField) evt.getComponent();

        if (jTxt.getSelectedText() != null && jTxt.getSelectedText().length()
                != jTxt.getText().length()) {
            evt.consume();
        } else if (jTxt.getSelectedText() == null && jTxt.getText().length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_jTxtKeyTyped

    private void minTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_minTxtKeyReleased
        switch (evt.getKeyCode()) {
            case java.awt.event.KeyEvent.VK_UP:
            case java.awt.event.KeyEvent.VK_DOWN:
            case java.awt.event.KeyEvent.VK_LEFT:
            case java.awt.event.KeyEvent.VK_RIGHT:
                return;
            default: {
                if (minTxt.getSelectedText() == null && Global.isNumber(minTxt.getText())
                        && (minTxt.getText().length() == 2
                        || evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)) {
                    secTxt.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_minTxtKeyReleased

    private void secTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_secTxtKeyReleased
        switch (evt.getKeyCode()) {
            case java.awt.event.KeyEvent.VK_UP:
            case java.awt.event.KeyEvent.VK_DOWN:
            case java.awt.event.KeyEvent.VK_LEFT:
            case java.awt.event.KeyEvent.VK_RIGHT:
                return;
            default: {
                if (secTxt.getSelectedText() == null && Global.isNumber(secTxt.getText())
                        && (secTxt.getText().length() == 2
                        || evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)) {
                    milTxt.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_secTxtKeyReleased

    private void milTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_milTxtKeyReleased
        switch (evt.getKeyCode()) {
            case java.awt.event.KeyEvent.VK_UP:
            case java.awt.event.KeyEvent.VK_DOWN:
            case java.awt.event.KeyEvent.VK_LEFT:
            case java.awt.event.KeyEvent.VK_RIGHT:
                return;
            default: {
                if (milTxt.getSelectedText() == null && Global.isNumber(milTxt.getText())
                        && (milTxt.getText().length() == 2
                        || evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)) {
                    okBtn.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_milTxtKeyReleased

    private void jTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtFocusLost
        JTextField jTxt = (JTextField) evt.getComponent();

        if (!Global.isNumber(jTxt.getText())) {
            jTxt.setText("00");
        } else {
            jTxt.setText(Time.normalizeFactor(jTxt.getText()));
        }
    }//GEN-LAST:event_jTxtFocusLost

    private void jTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtFocusGained
        JTextField jTxt = (JTextField) evt.getComponent();
        jTxt.selectAll();
    }//GEN-LAST:event_jTxtFocusGained

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        time.setMinutes(minTxt.getText());
        time.setSeconds(secTxt.getText());
        time.setMiliseconds(milTxt.getText());
        this.dispose();
    }//GEN-LAST:event_okBtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        time.setId(Global.NO_INDEX);
    }//GEN-LAST:event_formWindowClosing

    private void jTxtFocusLostNormalize(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtFocusLostNormalize
        if (!secTxt.getText().isBlank() && Global.isNumber(secTxt.getText())) {
            int min = Integer.parseInt(minTxt.getText());
            int sec = Integer.parseInt(secTxt.getText());

            if (sec > 60) {
                while (sec > 60) {
                    min = min != 99 ? min + 1 : min;
                    sec -= 60;

                }

                secTxt.setText(Time.normalizeFactor(String.valueOf(sec)));
                minTxt.setText(Time.normalizeFactor(String.valueOf(min)));
            }
        }
    }//GEN-LAST:event_jTxtFocusLostNormalize

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField milTxt;
    private javax.swing.JTextField minTxt;
    private javax.swing.JButton okBtn;
    private javax.swing.JTextField secTxt;
    // End of variables declaration//GEN-END:variables
}
